import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict


class ReportGenerator:
    """Generates professional resume reports in JSON and Markdown formats."""

    def __init__(self, output_dir: str | Path = "outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate_full_report(
        self,
        resume,
        ats_result,
        match_result,
        skill_gap,
        section_eval,
        summary,
        improvements,
        keywords_opt,
        job_description: str = "",
        extraction_error: str | None = None,
    ) -> Dict[str, Any]:
        report = {
            "report_generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "candidate_name": resume.full_name,
            "candidate_email": resume.email,
            "job_description": job_description,
            "extraction_error": extraction_error,
            "analysis_errors": self._collect_errors(
                ats_result,
                match_result,
                skill_gap,
                section_eval,
                summary,
                improvements,
                keywords_opt,
            ),
            "overall_scores": {
                "ats_score": self._round_score(self._get(ats_result, "overall_score")),
                "semantic_match": self._get(match_result, "overall_match_percentage", 0),
                "skill_gap_score": self._round_score(self._get(skill_gap, "skill_gap_score")),
                "section_quality": self._round_score(
                    self._get(section_eval, "overall_section_score")
                ),
                "keyword_optimization": self._round_score(
                    self._get(keywords_opt, "ats_optimization_score")
                ),
            },
            "professional_summary": self._get(summary, "summary", ""),
            "key_value_proposition": self._get(summary, "key_value_proposition", ""),
            "missing_critical_skills": self._get(skill_gap, "missing_critical_skills", []),
            "top_improvements": [
                self._get(item, "suggestion", "")
                for item in self._get(improvements, "suggestions", [])[:7]
                if self._get(item, "suggestion", "")
            ],
            "recommended_keywords": self._get(
                keywords_opt,
                "recommended_keywords",
                [],
            )[:15],
            "section_scores": {
                self._get(section, "section_name", "Unknown"): self._get(section, "score", 0)
                for section in self._get(section_eval, "sections", [])
            },
        }

        self._write_json(report)
        self._generate_markdown_report(report)

        print(f"Reports generated in '{self.output_dir}' folder")
        return report

    def _write_json(self, report: Dict[str, Any]) -> None:
        with (self.output_dir / "full_report.json").open("w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

    def _generate_markdown_report(self, report: Dict[str, Any]) -> None:
        """Create a clean, professional Markdown report."""
        missing_skills = self._markdown_list(report["missing_critical_skills"][:8])
        improvements = self._markdown_list(report["top_improvements"])
        keywords = self._markdown_list(report["recommended_keywords"])
        errors = self._markdown_errors(report["analysis_errors"])

        md_content = f"""# Resume Intelligence Report
**Generated on:** {report['report_generated_at']}

## Candidate Information
- **Name:** {report['candidate_name']}
- **Email:** {report.get('candidate_email') or 'N/A'}

## Overall Scores
| Metric                    | Score    |
|--------------------------|----------|
| ATS Compatibility        | {report['overall_scores']['ats_score']}/100 |
| Semantic Match           | {report['overall_scores']['semantic_match']}% |
| Skill Gap Alignment      | {report['overall_scores']['skill_gap_score']}/100 |
| Section Quality          | {report['overall_scores']['section_quality']}/100 |
| Keyword Optimization     | {report['overall_scores']['keyword_optimization']}/100 |

## AI Generated Professional Summary
{report['professional_summary'] or 'Not available.'}

## Key Value Proposition
{report['key_value_proposition'] or 'Not available.'}

## Critical Missing Skills
{missing_skills}

## Recommended Keywords
{keywords}

## Top Improvement Recommendations
{improvements}

## Analysis Notes
{errors}

## Next Steps
1. Add missing critical skills where they are accurate to your experience.
2. Quantify achievements with numbers.
3. Optimize keywords naturally.
4. Improve the summary section.

---
Generated by AI Resume Intelligence System
"""
        with (self.output_dir / "resume_analysis_report.md").open(
            "w",
            encoding="utf-8",
        ) as f:
            f.write(md_content)

        print("Markdown report saved: outputs/resume_analysis_report.md")

    def _collect_errors(self, *results) -> Dict[str, str]:
        names = [
            "ats_score",
            "semantic_match",
            "skill_gap_analysis",
            "section_evaluation",
            "professional_summary",
            "resume_improvements",
            "keyword_optimization",
        ]
        return {
            name: result["error"]
            for name, result in zip(names, results)
            if isinstance(result, dict) and result.get("error")
        }

    def _get(self, source, key: str, default=None):
        if source is None:
            return default
        if isinstance(source, dict):
            return source.get(key, default)
        return getattr(source, key, default)

    def _round_score(self, value) -> float:
        if value is None:
            return 0
        return round(float(value), 1)

    def _markdown_list(self, items) -> str:
        if not items:
            return "- Not available."
        return "\n".join(f"- {item}" for item in items)

    def _markdown_errors(self, errors: Dict[str, str]) -> str:
        if not errors:
            return "- All analyses completed successfully."
        return "\n".join(f"- {name}: {error}" for name, error in errors.items())
